name: Deploy to Azure Web App

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

  #  - name: Run tests
  #   run: |
  #     source venv/bin/activate
  #     pytest

    - name: Archive production artifacts
      run: |
        zip -r webapp.zip . -x "venv/*" -x "*.git/*" -x "*.github/*"

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      id: deploy-to-Gomedisys
      with:
        app-name: Clientcitas
        slot-name: production
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_465CE8976F3446768F4C53557A615198 }}
   #     package: webapp.zip
   #   continue-on-error: true

   # - name: Check deployment status and retry if failed
   #   run: |
   #     if [ "${{ steps.deploy.outcome }}" != "success" ]; then
   #      echo "First deployment attempt failed. Waiting and retrying..."
   #      sleep 30
   #      echo "Retrying deployment..."
   #       az webapp deployment source config-zip \
   #         --resource-group YOUR_RESOURCE_GROUP \
   #         --name YOUR_APP_NAME \
   #         --src webapp.zip
   #     fi
   
   #   env:
   #     AZURE_WEBAPP_PUBLISH_PROFILE: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
